import { SupModel } from '../sup-data';

export const belleData: Partial<SupModel> = {
  folderThumb: "https://i.ibb.co/5XTLyvpd/portrait.jpg",
  banner: {
    type: 'image',
    url: 'https://i.ibb.co/CsmrNqrj/Stripchat-Public-Show-f-Belle-Louise-Vp-2026-05-09-181248-preview.webp'
  },
  portrait: 'https://i.ibb.co/5XTLyvpd/portrait.jpg',
  bio: "BelleLouiseVp is a captivating model known for her expressive public performances and bold sensuality that has garnered her a massive following on Stripchat and beyond.",
  videos: [
    {
      id: "V2611",
      title: "BelleLouiseVP Ass & Pussy finguring",
      channel: [],
      tags: ["Ass", "Pussy Fingering", "Squirt"],
      src: "https://files.catbox.moe/ujujn8.mp4",
      thumb: "https://i.ibb.co/5XTLyvpd/portrait.jpg",
      duration: "394",
      addedAt: "2025-07-25T00:17:00Z",
      model: "BelleLouiseVp"
    }
  ],
  photos: [
    "https://i.ibb.co/TqNKBS4t/1753629892.webp",
    "https://i.ibb.co/tTTxTfgq/1774708890.webp",
    "https://i.ibb.co/3yHJxPy1/Fuck-hard-until-cum-squirt-men-s-bathroom.webp",
    "https://i.ibb.co/LF9ftF7/Fuck-hard-until-cum-squirt-mens-bathroom.webp",
    "https://i.ibb.co/bjZKW4RZ/Stripchat-Free-Chat-c-Belle-Louise-Vp-2026-06-04-000413-preview.webp",
    "https://i.ibb.co/7Htty2q/Stripchat-Free-Chat-c-Belle-Louise-Vp-2026-06-06-002019-preview.webp",
    "https://i.ibb.co/MDrmPjmv/Stripchat-Free-Chat-c-Belle-Louise-Vp-2026-06-06-224453-preview.webp",
    "https://i.ibb.co/KjKdFLN4/Stripchat-Free-Chat-c-Belle-Louise-Vp-2026-06-06-232449-preview.webp",
    "https://i.ibb.co/jZg4jCwq/Stripchat-Free-Chat-c-Belle-Louise-Vp-2026-06-10-000814-preview.webp",
    "https://i.ibb.co/H13Fts5/Stripchat-Free-Chat-c-Belle-Louise-Vp-2026-06-17-124147-preview.webp",
    "https://i.ibb.co/bR31VF2s/Stripchat-Free-Chat-c-Belle-Louise-Vp-2026-06-17-131353-preview.webp",
    "https://i.ibb.co/dJgwF8Tp/Stripchat-Free-Chat-c-Belle-Louise-Vp-2026-06-19-225250-preview.webp",
    "https://i.ibb.co/z1jjnj7/Stripchat-Free-Chat-c-Belle-Louise-Vp-2026-06-19-230422-preview.webp",
    "https://i.ibb.co/vxfL38SQ/Stripchat-Public-Show-f-Belle-Louise-Vp-2025-05-16-205855-preview.webp",
    "https://i.ibb.co/39J1YdPR/Stripchat-Public-Show-f-Belle-Louise-Vp-2025-06-25-214305-preview.webp",
    "https://i.ibb.co/Mk8q7FMd/Stripchat-Public-Show-f-Belle-Louise-Vp-2026-02-28-124443-preview.webp",
    "https://i.ibb.co/0y9JxZ4X/Stripchat-Public-Show-f-Belle-Louise-Vp-2026-02-28-153147-preview.webp",
    "https://i.ibb.co/Z1K8r5hS/Stripchat-Public-Show-f-Belle-Louise-Vp-2026-03-01-131831-preview.webp",
    "https://i.ibb.co/ZpCX60PJ/Stripchat-Public-Show-f-Belle-Louise-Vp-2026-03-01-144800-preview.webp",
    "https://i.ibb.co/hJ7ZPtcD/Stripchat-Public-Show-f-Belle-Louise-Vp-2026-03-15-124617-preview.webp",
    "https://i.ibb.co/CpKGL6jP/Stripchat-Public-Show-f-Belle-Louise-Vp-2026-04-08-112905-preview.webp",
    "https://i.ibb.co/VpDnn5w5/Stripchat-Public-Show-f-Belle-Louise-Vp-2026-04-08-232626-preview.webp",
    "https://i.ibb.co/3mgTqbTY/Stripchat-Public-Show-f-Belle-Louise-Vp-2026-04-09-003404-preview.webp",
    "https://i.ibb.co/rf02TnsJ/Stripchat-Public-Show-f-Belle-Louise-Vp-2026-05-01-132418-preview.webp",
    "https://i.ibb.co/8LbLJvcY/Stripchat-Public-Show-f-Belle-Louise-Vp-2026-05-09-153227-preview.webp",
    "https://i.ibb.co/CsmrNqrj/Stripchat-Public-Show-f-Belle-Louise-Vp-2026-05-09-181248-preview.webp"
  ],
  clips: [
    { title: "Pussy play hard", url: "https://files.catbox.moe/6prcpv.mp4" },
    { title: "SQUIRT INSIDE", url: "https://files.catbox.moe/nwdo8z.mp4" },
    { title: "Pussy Finguring", url: "https://files.catbox.moe/872nw5.mp4" },
    { title: "Pussy play", url: "https://files.catbox.moe/nk96qk.mp4" },
    { title: "Sexy pussy big dildo insdie make feel her!", url: "https://files.catbox.moe/p6aza7.mp4" },
    { title: "Showing ass", url: "https://files.catbox.moe/rmjtq5.mp4" },
    { title: "Squirt outside car park public", url: "https://files.catbox.moe/gj3lpv.mp4" },
    { title: "Bathroom bar finger pussy slap ass", url: "https://files.catbox.moe/zukfat.mp4" },
    { title: "Open door and squirt man touch me1", url: "https://files.catbox.moe/l9z5sk.mp4" },
    { title: "Open door and squirt man touch me", url: "https://files.catbox.moe/ld21et.mp4" },
    { title: "Show squirt WC Bar", url: "https://files.catbox.moe/oxo3ga.mp4" },
    { title: "private exclusive open just start bigass lovense public bigboobs naked hot", url: "https://files.catbox.moe/9xcqki.mp4" },
    { title: "Risky squirt1", url: "https://files.catbox.moe/qqrx8c.mp4" },
    { title: "Risky squirt", url: "https://files.catbox.moe/11ygfe.mp4" },
    { title: "All naked finger pussy bend over", url: "https://files.catbox.moe/e5xdo4.mp4" },
    { title: "Public Bathroom mall All naked play pussy", url: "https://files.catbox.moe/p3u48i.mp4" },
    { title: "All naked play pussy dildo squirt", url: "https://files.catbox.moe/xki6wt.mp4" },
    { title: "WC mall see my asshole twerk", url: "https://files.catbox.moe/3rmut9.mp4" },
    { title: "All naked fingers pussy", url: "https://files.catbox.moe/572jgh.mp4" },
    { title: "finger pussy spank ass", url: "https://files.catbox.moe/lkxn51.mp4" },
    { title: "Stranger touch me and see me squirt", url: "https://files.catbox.moe/k0zvsr.mp4" },
    { title: "Stranger SEE me SQUIRT bathroom Bar", url: "https://files.catbox.moe/uinfk9.mp4" },
    { title: "Squirt inside men's bathroom", url: "https://files.catbox.moe/og440a.mp4" },
    { title: "Stranger cum on my Ass and I kiss's balls and smel", url: "https://files.catbox.moe/eycgyp.mp4" },
    { title: "Stranger see me Squirt", url: "https://files.catbox.moe/pcx2ho.mp4" },
    { title: "Stripchat Free Chat c BelleLouiseVp 2026.06.07.132857 preview", url: "https://files.catbox.moe/hnl20p.mp4" },
    { title: "Big and long squirtRoom Topic", url: "https://files.catbox.moe/ss94se.mp4" },
    { title: "Squirt and stranger see this", url: "https://files.catbox.moe/dyezzp.mp4" },
    { title: "I'm going to masturbate a stranger until cum", url: "https://files.catbox.moe/t1dlhy.mp4" },
    { title: "Tiities", url: "https://files.catbox.moe/z55crh.mp4" },
    { title: "Fuck pissy and squirt", url: "https://files.catbox.moe/vh11s2.mp4" },
    { title: "Fuck pussy dildo blowjob", url: "https://files.catbox.moe/ne8re9.mp4" },
    { title: "SQUIRT Fuck pussy dildo blowjob", url: "https://files.catbox.moe/sniub2.mp4" },
    { title: "Play with dildo until squirt", url: "https://files.catbox.moe/ju9td6.mp4" },
    { title: "Play pussy until squirt", url: "https://files.catbox.moe/bzrldq.mp4" },
    { title: "I make Stranger cum on my body men's bathroom", url: "https://files.catbox.moe/11zppb.mp4" },
    { title: "Fuck hard until cum squirt men's bathroom", url: "https://files.catbox.moe/0kcl7d.mp4" },
    { title: "lick sucking a stranger penis head men's bathroom", url: "https://files.catbox.moe/bof1gv.mp4" },
    { title: "Stranger cum on my body 100 peoples buy blowjob", url: "https://files.catbox.moe/y86bq0.mp4" }
  ]
};
