import { SupModel } from '../sup-data';

export const fatimaData: Partial<SupModel> = {
  id: "fatima",
  name: "Amcute fatima",
  image: "https://i.ibb.co/Pz3DzQPy/profile.png",
  folderThumb: "https://i.ibb.co/Pz3DzQPy/profile.png",
  banner: {
    type: 'image',
    url: 'https://i.ibb.co/hrzxhZb/profile-banner.jpg'
  },
  portrait: 'https://i.ibb.co/Pz3DzQPy/profile.png',
  videos: [
    {
      id: "fatima-v1",
      title: "Amcute fatima Collection #1",
      tags: ["Exclusive", "New"],
      src: "https://bysekoze.com/d/cifdx410o2o0",
      thumb: "",
      duration: "619.2",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/ribi0g.mp4"
    },
    {
      id: "fatima-v2",
      title: "Amcute fatima Collection #2",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/t5oz50hipspe/2",
      thumb: "",
      duration: "542.4",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/r5jxil.mp4"
    },
    {
      id: "fatima-v3",
      title: "Amcute fatima Collection #3",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/lkc5iuq4llad/3",
      thumb: "",
      duration: "453.6",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/uq485v.mp4"
    },
    {
      id: "fatima-v4",
      title: "Amcute fatima Collection #4",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/mgqg7l0hd6wa/4",
      thumb: "",
      duration: "2589.6",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/4eiedv.mp4"
    },
    {
      id: "fatima-v5",
      title: "Amcute fatima Collection #5",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/4jm1dsydjsqb/5",
      thumb: "",
      duration: "1231.2",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/g42l6i.mp4"
    },
    {
      id: "fatima-v6",
      title: "Amcute fatima Collection #6",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/k16iflraa72g/6",
      thumb: "",
      duration: "1714.8",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/oqppaq.mp4"
    },
    {
      id: "fatima-v7",
      title: "Amcute fatima Collection #7",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/wrwx7r6bz9vy/7",
      thumb: "",
      duration: "1566",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/9hq37g.mp4"
    },
    {
      id: "fatima-v8",
      title: "Amcute fatima Collection #8",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/q2m5kurp94md/8",
      thumb: "",
      duration: "5353.2",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/oflz7s.mp4"
    },
    {
      id: "fatima-v9",
      title: "Amcute fatima Collection #9",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/orvdsjg4e6xn/9",
      thumb: "",
      duration: "1230.6",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/3x5lhw.mp4"
    },
    {
      id: "fatima-v10",
      title: "Amcute fatima Collection #10",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/9nhsf4x1cn5c/10",
      thumb: "",
      duration: "553.2",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/hjasee.mp4"
    },
    {
      id: "fatima-v11",
      title: "Amcute fatima Collection #11",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/sm5o52yolcv4/11",
      thumb: "",
      duration: "868.8",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/hgxxxx.mp4"
    },
    {
      id: "fatima-v12",
      title: "Amcute fatima Collection #12",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/zr03xwpgxcnp/1",
      thumb: "",
      duration: "606.6",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/m9zlcx.mp4"
    },
    {
      id: "fatima-v13",
      title: "Amcute fatima Collection #13",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/8gjamn2d42kq/2",
      thumb: "",
      duration: "436.8",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/hnv60r.mp4"
    },
    {
      id: "fatima-v14",
      title: "Amcute fatima Collection #14",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/j16qgn93dv52/3",
      thumb: "",
      duration: "565.8",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/yujerw.mp4"
    },
    {
      id: "fatima-v15",
      title: "Amcute fatima Collection #15",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/qygukd343fcd/4",
      thumb: "",
      duration: "634.2",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/pp5yd0.mp4"
    },
    {
      id: "fatima-v16",
      title: "Amcute fatima Collection #16",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/do4eao94imv9/5",
      thumb: "",
      duration: "272.4",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/nso2j9.mp4"
    },
    {
      id: "fatima-v17",
      title: "Amcute fatima Collection #17",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/crnnvn8cjfh6/6",
      thumb: "",
      duration: "84.6",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/b2x3nx.mp4"
    },
    {
      id: "fatima-v18",
      title: "Amcute fatima Collection #18",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/4n1a9iswgw3j/7",
      thumb: "",
      duration: "187.2",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/8t6nw1.mp4"
    },
    {
      id: "fatima-v19",
      title: "Amcute fatima Collection #19",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/4wck22s9if0e/8",
      thumb: "",
      duration: "209.4",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/tpwm9j.mp4"
    },
    {
      id: "fatima-v20",
      title: "Amcute fatima Collection #20",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/msclttnqdn36/9",
      thumb: "",
      duration: "129",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/38rq47.mp4"
    },
    {
      id: "fatima-v21",
      title: "Amcute fatima Collection #21",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/qoaoz0peoyxz/10",
      thumb: "",
      duration: "211.2",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/rc3iyf.mp4"
    },
    {
      id: "fatima-v22",
      title: "Amcute fatima Collection #22",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/glwqxfehbi3l/11",
      thumb: "",
      duration: "334.8",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/odi76n.mp4"
    },
    {
      id: "fatima-v23",
      title: "Amcute fatima Collection #23",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/4r4avet5x0jt/12",
      thumb: "",
      duration: "373.8",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/4py05k.mp4"
    },
    {
      id: "fatima-v24",
      title: "Amcute fatima Collection #24",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/s35o6qud8mct/13",
      thumb: "",
      duration: "387.6",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/h4mczs.mp4"
    },
    {
      id: "fatima-v25",
      title: "Amcute fatima Collection #25",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/8x5puh1b1l8q/14",
      thumb: "",
      duration: "267",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/sfq7r.mp4"
    },
    {
      id: "fatima-v26",
      title: "Amcute fatima Collection #26",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/qanx2xdmtjl4/15",
      thumb: "",
      duration: "202.2",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/v7e4m.mp4"
    },
    {
      id: "fatima-v27",
      title: "Amcute fatima Collection #27",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/40sx2ruruqpb/16",
      thumb: "",
      duration: "387.6",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/rbxgkr.mp4"
    },
    {
      id: "fatima-v28",
      title: "Amcute fatima Collection #28",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/t1vo650rh9j3/17",
      thumb: "",
      duration: "1205.4",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/5lhxyf.mp4"
    },
    {
      id: "fatima-v29",
      title: "Amcute fatima Collection #29",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/ch7uhv0qobup/18",
      thumb: "",
      duration: "373.8",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/cuf73b.mp4"
    },
    {
      id: "fatima-v30",
      title: "Amcute fatima Collection #30",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/exy094yonrqw/19",
      thumb: "",
      duration: "1269.6",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/d5zs39.mp4"
    },
    {
      id: "fatima-v31",
      title: "Amcute fatima Collection #31",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/ja9ymlohavd1/20",
      thumb: "",
      duration: "319.8",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/mj74g0.mp4"
    },
    {
      id: "fatima-v32",
      title: "Amcute fatima Collection #32",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/dooupggtrsff/21",
      thumb: "",
      duration: "1864.8",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/e7zxe5.mp4"
    },
    {
      id: "fatima-v33",
      title: "Amcute fatima Collection #33",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/l3iltrqz15pf/22",
      thumb: "",
      duration: "187.2",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/02jchw.mp4"
    },
    {
      id: "fatima-v34",
      title: "Amcute fatima Collection #34",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/1hmrcsfnn6m0/23",
      thumb: "",
      duration: "3848.4",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/slq39e.mp4"
    },
    {
      id: "fatima-v35",
      title: "Amcute fatima Collection #35",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/yi48xskdzc5o/24",
      thumb: "",
      duration: "1468.8",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/elrg21.mp4"
    },
    {
      id: "fatima-v36",
      title: "Amcute fatima Collection #36",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/e5s1du2gko0p/25",
      thumb: "",
      duration: "787.2",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/4i0kc.mp4"
    },
    {
      id: "fatima-v37",
      title: "Amcute fatima Collection #37",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/d/x4uydattkkjm/50",
      thumb: "",
      duration: "94.2",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/1q95pb.mp4"
    },
    {
      id: "fatima-v38",
      title: "Amcute fatima Collection #38",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/d/gbwwi5wax525/60",
      thumb: "",
      duration: "242.4",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/0sc5ip.mp4"
    },
    {
      id: "fatima-v39",
      title: "Amcute fatima Collection #39",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/d/742ux9i0m71k/70",
      thumb: "",
      duration: "204.6",
      model: "Amcute fatima",
      addedAt: "2026-07-10T12:00:00Z",
      previewUrl: "https://files.catbox.moe/f8jf82.mp4"
    },

  ],
  photos: [
    "https://i.ibb.co/pjnmyMMT/images-1.jpg",
    "https://i.ibb.co/zhfMSt5R/images-2.jpg",
    "https://i.ibb.co/MDynHZSP/images-3.jpg",
    "https://i.ibb.co/sd7v6bhG/images-4.jpg",
    "https://i.ibb.co/3ynY4G3Q/images-5.jpg",
    "https://i.ibb.co/6J7xHPXf/images-6.jpg",
    "https://i.ibb.co/zThFMwVm/images-7.jpg",
    "https://i.ibb.co/n87z7hgK/images-8.jpg",
    "https://i.ibb.co/zhNzvBz9/images-9.jpg",
    "https://i.ibb.co/M59NBnPX/images-10.jpg",
    "https://i.ibb.co/nM9j4b09/images.jpg"
  ]
};
