import { SupModel } from '../sup-data';

export const muskan_1Data: Partial<SupModel> = {
  portrait: 'https://i.ibb.co/6J0qQ7F8/Portrait.jpg',
  folderThumb: 'https://i.ibb.co/LdRdkRmr/Fodlethumb.png',
  image: 'https://i.ibb.co/6J0qQ7F8/Portrait.jpg',
  videos: [
    {
      id: "muskan1-v1",
      title: "Rubbing vibrator in pussy",
      channel: [],
      tags: ["Blowjob"],
      src: "https://bysekoze.com/d/6tdh0eeta58b/rubbing-vibrator-in-pussy",
      thumb: "https://i.ibb.co/j97PHrg2/Rubbing-vibrator-in-pussy-frame-at-0m40s.jpg",
      overlay: "https://i.ibb.co/4RpJSmc9/Rubbing-vibrator-in-pussy.jpg",
      duration: "761",
      previewUrl: "https://files.catbox.moe/jmwpnk.mp4",
    },
    {
      id: "muskan1-v2",
      title: "Muskan 1 Collection #2",
      channel: [],
      tags: ["Exclusive"],
      src: "https://xpornium.net/embed/w19mz4mef1dkjo",
      thumb: "https://i.ibb.co/gZRmNmkF/w19mz4mef1dkjo-4x4.jpg",
      duration: "8400",
    },
    {
      id: "muskan1-v3",
      title: "Muskan 1 Collection #3",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/jb4pjio7634v/1",
      thumb: "",
      overlay: "https://i.ibb.co/ksy3BQvt/1.jpg",
      duration: "4213",
      previewUrl: "https://files.catbox.moe/6vgrmb.mp4",
    },
    {
      id: "muskan1-v4",
      title: "Muskan 1 Collection #4",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/aeeo51cm78zx/2",
      thumb: "",
      overlay: "https://i.ibb.co/9m19ygbp/2.jpg",
      duration: "376",
      previewUrl: "https://files.catbox.moe/eqzo66.mp4",
    },
    {
      id: "muskan1-v5",
      title: "Muskan 1 Collection #5",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/cez8fhy3palq/3",
      thumb: "",
      overlay: "https://i.ibb.co/fGD1r2Qg/3.jpg",
      duration: "9361",
      previewUrl: "https://files.catbox.moe/mc0enj.mp4",
    },
    {
      id: "muskan1-v6",
      title: "Muskan 1 Collection #6",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/j3pwf9b961fl/4",
      thumb: "",
      overlay: "https://i.ibb.co/vxXSNww1/4.jpg",
      duration: "5427",
      previewUrl: "https://files.catbox.moe/1p1qg6.mp4",
    },
    {
      id: "muskan1-v7",
      title: "Muskan 1 Collection #7",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/s1o42qmke58n/5",
      thumb: "",
      overlay: "https://i.ibb.co/rG6pCMR5/5.jpg",
      duration: "3507",
      previewUrl: "https://files.catbox.moe/0hkab6.mp4",
    },
    {
      id: "muskan1-v8",
      title: "Muskan 1 Collection #8",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/shj63zt9g0g3/6",
      thumb: "",
      overlay: "https://i.ibb.co/2YWFsyVk/6.jpg",
      duration: "445",
      previewUrl: "https://files.catbox.moe/76m61c.mp4",
    },
    {
      id: "muskan1-v9",
      title: "Muskan 1 Collection #9",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/0984734r0d9h/7",
      thumb: "",
      overlay: "https://i.ibb.co/zT4TRVc1/7.jpg",
      duration: "2215",
      previewUrl: "https://files.catbox.moe/65husy.mp4",
    },
    {
      id: "muskan1-v10",
      title: "Muskan 1 Collection #10",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/6rmxvr0j75i0/8",
      thumb: "",
      overlay: "https://i.ibb.co/rRTcFNG1/8.jpg",
      duration: "909",
      previewUrl: "https://files.catbox.moe/powo7q.mp4",
    },
    {
      id: "muskan1-v11",
      title: "Muskan 1 Collection #11",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/vl9ajooxan98/9",
      thumb: "",
      overlay: "https://i.ibb.co/Kx9fJ8Bt/9.jpg",
      duration: "4353",
      previewUrl: "https://files.catbox.moe/2o8gxc.mp4",
    },
    {
      id: "muskan1-v12",
      title: "Muskan 1 Collection #12",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/45xjfvwb01ac/10",
      thumb: "",
      overlay: "https://i.ibb.co/pBGDCb5f/10.jpg",
      duration: "1024",
      previewUrl: "https://files.catbox.moe/2s9rot.mp4",
    },
    {
      id: "muskan1-v13",
      title: "Muskan 1 Collection #13",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/f2kaqd7gdsjy/11",
      thumb: "",
      overlay: "https://i.ibb.co/3yWpCmXs/11.jpg",
      duration: "1378",
      previewUrl: "https://files.catbox.moe/zxetid.mp4",
    },
    {
      id: "muskan1-v14",
      title: "Muskan 1 Collection #14",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/tbzkha51e4d4/12",
      thumb: "",
      overlay: "https://i.ibb.co/27Y1Tj4W/12.jpg",
      duration: "9066",
      previewUrl: "https://files.catbox.moe/x0lg0.mp4",
    },
    {
      id: "muskan1-v15",
      title: "Muskan 1 Collection #15",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/jv0krfc5den0/13",
      thumb: "",
      overlay: "https://i.ibb.co/1tkCw5wx/13.jpg",
      duration: "1272",
      previewUrl: "https://files.catbox.moe/krdgeb.mp4",
    },
    {
      id: "muskan1-v16",
      title: "Muskan 1 Collection #16",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/rw8ty1m6e1ia/14",
      thumb: "",
      overlay: "https://i.ibb.co/KpgH0p8p/14.jpg",
      duration: "3239",
      previewUrl: "https://files.catbox.moe/pjw036.mp4",
    },
    {
      id: "muskan1-v17",
      title: "Muskan 1 Collection #17",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/9035mcxfwb8a/15",
      thumb: "",
      overlay: "https://i.ibb.co/N0X7gfJ/15.jpg",
      duration: "1316",
      previewUrl: "https://files.catbox.moe/zvqvt0.mp4",
    },
    {
      id: "muskan1-v18",
      title: "Muskan 1 Collection #18",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/n098mh2k0fyu/16",
      thumb: "",
      overlay: "https://i.ibb.co/cKwC98Nx/16.jpg",
      duration: "6491",
      previewUrl: "https://files.catbox.moe/n1bb72.mp4",
    },
    {
      id: "muskan1-v19",
      title: "Muskan 1 Collection #19",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/832lrknb6duq/17",
      thumb: "",
      overlay: "https://i.ibb.co/qMm0bmkW/17.jpg",
      duration: "4248",
      previewUrl: "https://files.catbox.moe/s0nooy.mp4",
    },
    {
      id: "muskan1-v20",
      title: "Muskan 1 Collection #20",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/mv97h24173o3/18",
      thumb: "",
      overlay: "https://i.ibb.co/9mf6f7q4/18.jpg",
      duration: "1522",
      previewUrl: "https://files.catbox.moe/4lh5g3.mp4",
    },
    {
      id: "muskan1-v21",
      title: "Muskan 1 Collection #21",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/5j8skfrfdo3o/19",
      thumb: "",
      overlay: "https://i.ibb.co/tM8hKgFq/19.jpg",
      duration: "6556",
      previewUrl: "https://files.catbox.moe/xoux2c.mp4",
    },
    {
      id: "muskan1-v22",
      title: "Muskan 1 Collection #22",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/0i5icotlwv28/20",
      thumb: "",
      overlay: "https://i.ibb.co/N6y6RLnG/20.jpg",
      duration: "1160",
      previewUrl: "https://files.catbox.moe/gl6b7d.mp4",
    },
    {
      id: "muskan1-v23",
      title: "Muskan 1 Collection #23",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/n9zuyijhgavx/21",
      thumb: "",
      overlay: "https://i.ibb.co/zWm1tLGH/21.jpg",
      duration: "1495",
      previewUrl: "https://files.catbox.moe/cp14k6.mp4",
    },
    {
      id: "muskan1-v24",
      title: "Muskan 1 Collection #24",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/fl1bv67h4jdz/22",
      thumb: "",
      overlay: "https://i.ibb.co/G483SdRZ/22.jpg",
      duration: "1212",
      previewUrl: "https://files.catbox.moe/vyur38.mp4",
    },
    {
      id: "muskan1-v25",
      title: "Muskan 1 Collection #25",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/5nh8rnl0qyx5/23",
      thumb: "",
      overlay: "https://i.ibb.co/Rk6TcQF0/23.jpg",
      duration: "1628",
      previewUrl: "https://files.catbox.moe/k71cdu.mp4",
    },
    {
      id: "muskan1-v26",
      title: "Muskan 1 Collection #26",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/waaboizkb9nl/24",
      thumb: "",
      overlay: "https://i.ibb.co/twJ1fZsw/24.jpg",
      duration: "1030",
      previewUrl: "https://files.catbox.moe/ebo839.mp4",
    },
    {
      id: "muskan1-v27",
      title: "Muskan 1 Collection #27",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/v6qmtenzj2ii/25",
      thumb: "",
      overlay: "https://i.ibb.co/YBXxz596/25.jpg",
      duration: "1025",
      previewUrl: "https://files.catbox.moe/rdepex.mp4",
    },
    {
      id: "muskan1-v28",
      title: "Muskan 1 Collection #28",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/w5u1bif23ldh/26",
      thumb: "",
      overlay: "https://i.ibb.co/gL4h3hMQ/26.jpg",
      duration: "3862",
      previewUrl: "https://files.catbox.moe/f3nnjo.mp4",
    },
    {
      id: "muskan1-v29",
      title: "Muskan 1 Collection #29",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/evk4hyjav42w/27",
      thumb: "",
      overlay: "https://i.ibb.co/Mxy9FwZQ/27.jpg",
      duration: "3657",
      previewUrl: "https://files.catbox.moe/zz9x99.mp4",
    },
    {
      id: "muskan1-v30",
      title: "Muskan 1 Collection #30",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/ox94a32kisc2/28",
      thumb: "",
      overlay: "https://i.ibb.co/d4008Pm7/28.jpg",
      duration: "110",
      previewUrl: "https://files.catbox.moe/dvn881.mp4",
    },
    {
      id: "muskan1-v31",
      title: "Muskan 1 Collection #31",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/m3a9iis9q0jg/29",
      thumb: "",
      overlay: "https://i.ibb.co/0pNvb75B/29.jpg",
      duration: "3853",
      previewUrl: "https://files.catbox.moe/wr9pz5.mp4",
    },
    {
      id: "muskan1-v32",
      title: "Muskan 1 Collection #32",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/2vby6akfam3w/30",
      thumb: "",
      overlay: "https://i.ibb.co/SDbwFDnP/30.jpg",
      duration: "2421",
      previewUrl: "https://files.catbox.moe/f64lie.mp4",
    },
    {
      id: "muskan1-v33",
      title: "Muskan 1 Collection #33",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/rvpeci4cbspv/31",
      thumb: "",
      overlay: "https://i.ibb.co/TDFS5FSz/31.jpg",
      duration: "3022",
      previewUrl: "https://files.catbox.moe/r3b8q5.mp4",
    },
    {
      id: "muskan1-v34",
      title: "Muskan 1 Collection #34",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/we2iknb1r9qh/32",
      thumb: "",
      overlay: "https://i.ibb.co/G31Xj7qT/32.jpg",
      duration: "1201",
      previewUrl: "https://files.catbox.moe/0md3mb.mp4",
    },
    {
      id: "muskan1-v35",
      title: "Muskan 1 Collection #35",
      channel: [],
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/s8fuus9vrapk/33",
      thumb: "",
      overlay: "https://i.ibb.co/pC71sTq/33.jpg",
      duration: "1763",
      previewUrl: "https://files.catbox.moe/jz55mu.mp4",
    }
  ],
  photos: [
    "https://i.ibb.co/HfP0188v/3fd25b0d-32ba-4eec-9d3a-931d7b3a440b.webp",
    "https://i.ibb.co/BXMWsGT/9bb98cb9-2b85-496c-8a0d-54aa5af23b7f.webp",
    "https://i.ibb.co/XZyLT3W4/25ad0a1c-3c33-4d6c-863a-b84ff379ad0a.webp",
    "https://i.ibb.co/HLRdxhwn/52a2295f-94a3-4a36-9c09-81dd96e141d4.webp",
    "https://i.ibb.co/Nd5LK98x/71e4500c-1456-4e9a-b31c-56b26fb07d7a.webp",
    "https://i.ibb.co/R4hNpbn9/778f224d-7486-4fa2-8d89-64e0e4787c12.webp",
    "https://i.ibb.co/Fkwx6nM9/05891ac6-1bc8-4094-b250-697d88813b4c.webp",
    "https://i.ibb.co/qYQwG2WZ/25008ede-b947-493f-b7ca-1c7f5cc9b8f9.webp",
    "https://i.ibb.co/rfXs1v21/a72130f4-761a-49f8-9815-9873f186455f.webp",
    "https://i.ibb.co/3yM6QztW/a2190238-da5b-4006-ad67-cb162536801b.webp",
    "https://i.ibb.co/9mSbWJGN/ca1b0aee-22b2-4952-a77a-47ee3bbc44eb.webp",
    "https://i.ibb.co/8LYvz4r3/50ec06dfb5fc0bfd46afa7940ceec9a6.webp",
    "https://i.ibb.co/x86ZbzT9/1732509729.webp",
    "https://i.ibb.co/YBT3GKd9/aaa22887c6747be4a12c1854b3c684fb.webp",
    "https://i.ibb.co/67N0gZDN/b70ddaf0bd543d4b7ec529ea7c7c4fa1.webp",
    "https://i.ibb.co/hQznvMR/b5538d92a10b2c88a8455ce07af06664.webp",
    "https://i.ibb.co/NgxNJ91s/cb42774c1adbd37121b9b2bb9fbdd071.webp",
    "https://i.ibb.co/LdRdkRmr/Fodlethumb.png",
    "https://i.ibb.co/LDc4nyyp/Monster-Dildo-Double-penetration.jpg",
    "https://i.ibb.co/BHx7wgBJ/Monster-dildo-Ass-to-mouth.jpg",
    "https://i.ibb.co/6JZg7SCK/Playing-Cucumber.jpg",
    "https://i.ibb.co/6J0qQ7F8/Portrait.jpg",
    "https://i.ibb.co/RTrZkR9M/Torturing-me-I-know-you-like-seeing-me-weeping-and-screaming.jpg"
  ],
  clips: [
    {
      title: "Short Clip 1",
      url: "https://files.catbox.moe/sgq7l7.mp4",
      thumbnail: ""
    }
  ]
};
