import { SupModel } from '../sup-data';

export const sexy_jenny_Data: Partial<SupModel> = {
  portrait: 'https://i.ibb.co/C3PmpRRP/porrait.jpg',
  folderThumb: 'https://i.ibb.co/mFPrwJrM/Foderthumb.webp',
  image: 'https://i.ibb.co/C3PmpRRP/porrait.jpg',
  photos: [
    "https://i.ibb.co/1JbKGvQx/0a490de9fba36477e8985934107fb2f3.webp",
    "https://i.ibb.co/n8czjftw/07eee3b3986855cf5f463dfb21c2f029.webp",
    "https://i.ibb.co/Kz2Ymj98/64dbff367ad445cf6af67c171d1e6dc3.webp",
    "https://i.ibb.co/KcwHKdWg/826466fde5fb9bf5cb228d961aed58df.jpg",
    "https://i.ibb.co/mFPrwJrM/Foderthumb.webp",
    "https://i.ibb.co/C3PmpRRP/porrait.jpg"
  ],
  clips: [
    { title: "Short Clip 1", url: "https://files.catbox.moe/fuuh94.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 2", url: "https://files.catbox.moe/e3p73l.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 3", url: "https://files.catbox.moe/unjsrc.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 4", url: "https://files.catbox.moe/246js9.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 5", url: "https://files.catbox.moe/1k7in9.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 6", url: "https://files.catbox.moe/zj1ii7.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 7", url: "https://files.catbox.moe/9kjbxr.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 8", url: "https://files.catbox.moe/f60dgi.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 9", url: "https://files.catbox.moe/htppd3.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 10", url: "https://files.catbox.moe/wrf27w.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 11", url: "https://files.catbox.moe/segxmw.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 12", url: "https://files.catbox.moe/zxc8xr.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 13", url: "https://files.catbox.moe/y9r07u.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 14", url: "https://files.catbox.moe/f8c9sx.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 15", url: "https://files.catbox.moe/23jphc.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 16", url: "https://files.catbox.moe/cwk3je.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 17", url: "https://files.catbox.moe/6r1m8h.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 18", url: "https://files.catbox.moe/wzxzy9.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 19", url: "https://files.catbox.moe/kmzks4.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 20", url: "https://files.catbox.moe/94vqyh.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 21", url: "https://files.catbox.moe/2r0dd4.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 22", url: "https://files.catbox.moe/xru8pl.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 23", url: "https://files.catbox.moe/l8gd85.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 24", url: "https://files.catbox.moe/6elafw.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 25", url: "https://files.catbox.moe/zr6o4d.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 26", url: "https://files.catbox.moe/l5ighw.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 27", url: "https://files.catbox.moe/v5yhnb.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 28", url: "https://files.catbox.moe/8qrw50.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 29", url: "https://files.catbox.moe/9rd2ia.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 30", url: "https://files.catbox.moe/7k2zjv.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 31", url: "https://files.catbox.moe/pph4s8.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 32", url: "https://files.catbox.moe/ahthwa.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
    { title: "Short Clip 33", url: "https://files.catbox.moe/wvp97x.mp4", thumbnail: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp" },
  ],
  videos: [
    { id: "sj-c1", title: "Short Clip 1", src: "https://files.catbox.moe/fuuh94.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c2", title: "Short Clip 2", src: "https://files.catbox.moe/e3p73l.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c3", title: "Short Clip 3", src: "https://files.catbox.moe/unjsrc.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c4", title: "Short Clip 4", src: "https://files.catbox.moe/246js9.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c5", title: "Short Clip 5", src: "https://files.catbox.moe/1k7in9.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c6", title: "Short Clip 6", src: "https://files.catbox.moe/zj1ii7.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c7", title: "Short Clip 7", src: "https://files.catbox.moe/9kjbxr.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c8", title: "Short Clip 8", src: "https://files.catbox.moe/f60dgi.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c9", title: "Short Clip 9", src: "https://files.catbox.moe/htppd3.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c10", title: "Short Clip 10", src: "https://files.catbox.moe/wrf27w.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c11", title: "Short Clip 11", src: "https://files.catbox.moe/segxmw.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c12", title: "Short Clip 12", src: "https://files.catbox.moe/zxc8xr.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c13", title: "Short Clip 13", src: "https://files.catbox.moe/y9r07u.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c14", title: "Short Clip 14", src: "https://files.catbox.moe/f8c9sx.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c15", title: "Short Clip 15", src: "https://files.catbox.moe/23jphc.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c16", title: "Short Clip 16", src: "https://files.catbox.moe/cwk3je.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c17", title: "Short Clip 17", src: "https://files.catbox.moe/6r1m8h.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c18", title: "Short Clip 18", src: "https://files.catbox.moe/wzxzy9.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c19", title: "Short Clip 19", src: "https://files.catbox.moe/kmzks4.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c20", title: "Short Clip 20", src: "https://files.catbox.moe/94vqyh.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c21", title: "Short Clip 21", src: "https://files.catbox.moe/2r0dd4.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c22", title: "Short Clip 22", src: "https://files.catbox.moe/xru8pl.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c23", title: "Short Clip 23", src: "https://files.catbox.moe/l8gd85.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c24", title: "Short Clip 24", src: "https://files.catbox.moe/6elafw.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c25", title: "Short Clip 25", src: "https://files.catbox.moe/zr6o4d.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c26", title: "Short Clip 26", src: "https://files.catbox.moe/l5ighw.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c27", title: "Short Clip 27", src: "https://files.catbox.moe/v5yhnb.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c28", title: "Short Clip 28", src: "https://files.catbox.moe/8qrw50.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c29", title: "Short Clip 29", src: "https://files.catbox.moe/9rd2ia.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c30", title: "Short Clip 30", src: "https://files.catbox.moe/7k2zjv.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c31", title: "Short Clip 31", src: "https://files.catbox.moe/pph4s8.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c32", title: "Short Clip 32", src: "https://files.catbox.moe/ahthwa.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "sj-c33", title: "Short Clip 33", src: "https://files.catbox.moe/wvp97x.mp4", thumb: "https://i.ibb.co/mFPrwJrM/Foderthumb.webp", categories: ["Stripchat", "Short Clips"] },
  ]
};
