import { SupModel } from '../sup-data';

export const winterforuData: Partial<SupModel> = {
  portrait: 'https://i.ibb.co/gFP89s4T/Porrarit.png',
  folderThumb: 'https://i.ibb.co/r2zZ4tt9/Folderthumb.webp',
  image: 'https://i.ibb.co/gFP89s4T/Porrarit.png',
  photos: [
    "https://i.ibb.co/spqmPtR0/1b8b05557bdc36286e62043353c49bf9.webp",
    "https://i.ibb.co/JRyc4CqH/407a85c0f2cd26490f5bf4959bd22c7f.webp",
    "https://i.ibb.co/MycYS42b/1440e933b85efde5cce2c273073f70b4.webp",
    "https://i.ibb.co/LHKbTnh/08336eb79200aeae4b92f4e28f6326c3.webp",
    "https://i.ibb.co/5h3Mz0hc/244592f5d81036eda14a1384bd2a9bda.webp",
    "https://i.ibb.co/v6mwqb2Y/b8d0aa2aca77817faa696b4da2082643.webp",
    "https://i.ibb.co/YrvmTCg/e07f93609ba564f74ffcced20f80bf9a.webp",
    "https://i.ibb.co/ns946Ksp/efffedae07f09dfbe5e39f6bc2f3acf0.webp",
    "https://i.ibb.co/whg0G90m/f40ef58894228304815dbaa876518543.webp",
    "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp",
    "https://i.ibb.co/gFP89s4T/Porrarit.png",
    "https://i.ibb.co/Pv4qGNWZ/profile-3.png"
  ],
  clips: [
    { title: "Short Clip 1", url: "https://files.catbox.moe/vcuwq4.mp4" },
    { title: "Short Clip 2", url: "https://files.catbox.moe/i9kfs6.mp4" },
    { title: "Short Clip 3", url: "https://files.catbox.moe/27gqcj.mp4" },
    { title: "Short Clip 4", url: "https://files.catbox.moe/rl2axp.mp4" },
    { title: "Short Clip 5", url: "https://files.catbox.moe/i5kkvp.mp4" },
    { title: "Short Clip 6", url: "https://files.catbox.moe/758ee6.mp4" },
    { title: "Short Clip 7", url: "https://files.catbox.moe/5e0e1l.mp4" },
    { title: "Short Clip 8", url: "https://files.catbox.moe/h9oksm.mp4" },
    { title: "Short Clip 9", url: "https://files.catbox.moe/uwdx3y.mp4" },
    { title: "Short Clip 10", url: "https://files.catbox.moe/toctcf.mp4" },
    { title: "Short Clip 11", url: "https://files.catbox.moe/b09pkk.mp4" },
    { title: "Short Clip 12", url: "https://files.catbox.moe/6e7dj4.mp4" },
    { title: "Short Clip 13", url: "https://files.catbox.moe/fnuxp6.mp4" },
    { title: "Short Clip 14", url: "https://files.catbox.moe/upxliq.mp4" },
    { title: "Short Clip 15", url: "https://files.catbox.moe/asbn6u.mp4" },
    { title: "Short Clip 16", url: "https://files.catbox.moe/yrz9yw.mp4" },
    { title: "Short Clip 17", url: "https://files.catbox.moe/j4a6dd.mp4" },
    { title: "Short Clip 18", url: "https://files.catbox.moe/wbh071.mp4" },
    { title: "Short Clip 19", url: "https://files.catbox.moe/xjo1c6.mp4" },
  ],
  videos: [
    {
      id: "wf-v0",
      title: "Winterforu - My Stripchat Stream",
      tags: ["Stripchat", "Private"],
      src: "https://xpornium.net/embed/vg9mjg9lap2zoy",
      thumb: "https://i.ibb.co/1tj7fxNP/wmremove-transformed.png",
      duration: "10800",
      addedAt: "2026-07-08T12:00:00Z",
      model: "Winterforu",
      description: "Winterforu - My Stripchat Stream",
      gallery: [],
      previewUrl: ""
    },
    {
      id: "wf-v1",
      title: "Winterforu - My Stripchat Stream",
      tags: ["Stripchat", "Private"],
      src: "https://bysekoze.com/e/rplrwr2ii1yf/1",
      thumb: "",
      duration: "2725.8",
      addedAt: "2026-07-08T12:00:00Z",
      model: "Winterforu",
      description: "Winterforu - My Stripchat Stream",
      gallery: [],
      previewUrl: "https://files.catbox.moe/hkmvo7.mp4"
    },
    {
      id: "wf-v2",
      title: "Winterforu Collection #2",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/dxp8qkw05tbp/2",
      thumb: "",
      duration: "2612.4",
      addedAt: "2026-07-11T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/wbh07i.mp4"
    },
    {
      id: "wf-v3",
      title: "Winterforu Collection #3",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/lmv3frwej03j/4",
      thumb: "",
      duration: "11126.4",
      addedAt: "2026-07-11T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/yrz9yw.mp4"
    },
    {
      id: "wf-v4",
      title: "Winterforu Collection #4",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/3662j0bzok30/5",
      thumb: "",
      duration: "4764.6",
      addedAt: "2026-07-11T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/yrz9yw.mp4"
    },
    {
      id: "wf-v5",
      title: "Winterforu Collection #5",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/gcxuelio7qof/6",
      thumb: "",
      overlay: "https://i.ibb.co/4Zfp8FGd/z1dq7636td9gl4-4x4.jpg",
      duration: "843.6",
      addedAt: "2026-07-11T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/asbn6u.mp4"
    },
    {
      id: "wf-v6",
      title: "Winterforu Collection #6",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/bptbs2jsyog7/7",
      thumb: "",
      duration: "3994.8",
      addedAt: "2026-07-11T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/toctcf.mp4"
    },
    {
      id: "wf-v7",
      title: "Winterforu Collection #7",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/qi07ck3cnwku/8",
      thumb: "",
      duration: "495.6",
      addedAt: "2026-07-11T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/6e7dj4.mp4"
    },
    {
      id: "wf-v8",
      title: "Winterforu Collection #8",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/flhlnvriv020/9",
      thumb: "",
      duration: "1441.8",
      addedAt: "2026-07-11T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/h9oksm.mp4"
    },
    {
      id: "wf-v9",
      title: "Winterforu Collection #9",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/kf8cb29f0qdf/10",
      thumb: "",
      duration: "12725.4",
      addedAt: "2026-07-11T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/5e0el1.mp4"
    },
    {
      id: "wf-v10",
      title: "Winterforu Collection #10",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/dsgeohprrm8t/11",
      thumb: "",
      duration: "8727.6",
      addedAt: "2026-07-11T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/6i08y5.mp4"
    },
    {
      id: "wf-v11",
      title: "Winterforu Collection #11",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/dkxfn2t0qq7b/12",
      thumb: "",
      duration: "4321.8",
      addedAt: "2026-07-11T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/i5kkvp.mp4"
    },
    {
      id: "wf-v12",
      title: "Winterforu Collection #12",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/sod5ni3fru84/13",
      thumb: "",
      duration: "1393.2",
      addedAt: "2026-07-11T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/rt2axp.mp4"
    },
    {
      id: "wf-v13",
      title: "Winterforu Collection #13",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/m161rdryvgf5/14",
      thumb: "",
      duration: "13229.4",
      addedAt: "2026-07-11T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/27gqcj.mp4"
    },
    {
      id: "wf-v14",
      title: "Winterforu Collection #14",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/oxnypgj7n4gt/15",
      thumb: "",
      duration: "1167.6",
      addedAt: "2026-07-11T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/i9kfs6.mp4"
    },
    {
      id: "wf-v15",
      title: "Winterforu Collection #15",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/3uy8l5cvsr3h/16",
      thumb: "",
      duration: "2592.6",
      addedAt: "2026-07-11T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/21nk2i.mp4"
    },
    {
      id: "wf-v16",
      title: "Winterforu Collection #16",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/hytec9jjemik/17",
      thumb: "",
      duration: "2532",
      addedAt: "2026-07-11T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/1ngzoy.mp4"
    },
    {
      id: "wf-v17",
      title: "Winterforu Collection #17",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/34sxe86vcs9s/18",
      thumb: "",
      duration: "3184.8",
      addedAt: "2026-07-11T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/m55q2b.mp4"
    },
    {
      id: "wf-v18",
      title: "Winterforu Collection #18",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/h26bgh49uurc/19",
      thumb: "",
      duration: "4576.8",
      addedAt: "2026-07-11T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/3g63s2.mp4"
    },
     {
      id: "wf-v19",
      title: "Winterforu Collection #19",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/csopbrdaelcq/20",
      thumb: "",
      duration: "7408.2",
      addedAt: "2026-07-11T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/xzr4ey.mp4"
    },
    {
      id: "wf-v20",
      title: "Handcuffed Winterforu Fingers Her Clit and Pinches Boobs Harder",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/srsska7rk35d/handcuffed-winterforu-fingers-her-clit-and-pinches-boobs-harder",
      thumb: "",
      overlay: "https://i.ibb.co/m5fxfghp/Handcuffed-Winterforu-Fingers-Her-Clit-and-Pinches-Boobs-Harder.jpg",
      duration: "3884",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/mt8d5d.mp4"
    },
    {
      id: "wf-v21",
      title: "Hot India girl boob show",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/answq8309cpt/hot-india-girl-boob-show",
      thumb: "",
      overlay: "https://i.ibb.co/gFh3VFzC/Hot-India-girl-boob-show.jpg",
      duration: "343",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/j0l8dl.mp4"
    },
    {
      id: "wf-v22",
      title: "Hot Winterforu Teases in White dress & Panty Before Intense BDSM Clit Torture and Big Boobs Punishment",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/08k07hh1rre8/hot-winterforu-teases-in-white-dress-panty-before-intense-bdsm-clit-torture-and-big-boobs-punishment",
      thumb: "",
      overlay: "https://i.ibb.co/9MrFWRY/Hot-Winterforu-Teases-in-White-dress-Panty-Before-Intense-BDSM-Clit-Torture-and-Big-Boobs-Punishme.jpg",
      duration: "1263",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/k61wmh.mp4"
    },
    {
      id: "wf-v23",
      title: "Put Finger in Her Ass and Sexy Oiled Body",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/o5m8lzdnojrc/put-finger-in-her-ass-and-sexy-oiled-body",
      thumb: "",
      overlay: "https://i.ibb.co/8LSw6jLj/Put-Finger-in-Her-Ass-and-Sexy-Oiled-Body.jpg",
      duration: "965",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/54mza8.mp4"
    },
    {
      id: "wf-v24",
      title: "Sexy Winterforu in White Mesh Top and Tiny Panties",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/0n9q6gwtebc4/sexy-winterforu-in-white-mesh-top-and-tiny-panties",
      thumb: "",
      overlay: "https://i.ibb.co/QFkbtvxG/Sexy-Winterforu-in-White-Mesh-Top-and-Tiny-Panties.jpg",
      duration: "1568",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/6qa4oq.mp4"
    },
    {
      id: "wf-v25",
      title: "Stripchat Winterforu Nipple clint and blowjob dildo",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/1rtxhm4ebcq8/stripchat-winterforu-nipple-clint-and-blowjob-dildo",
      thumb: "",
      overlay: "https://i.ibb.co/tP8ZzwHW/Stripchat-Winterforu-Nipple-clint-and-blowjob-dildo.jpg",
      duration: "4324",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/4310p4.mp4"
    },
    {
      id: "wf-v26",
      title: "Stripchat Winterforu playing with boobs harder",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/mpjoqcvuyrc0/stripchat-winterforu-playing-with-boobs-harder",
      thumb: "",
      overlay: "https://i.ibb.co/TDNpTd5R/Stripchat-Winterforu-playing-with-boobs-harder.jpg",
      duration: "848",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/8wjf2g.mp4"
    },
    {
      id: "wf-v27",
      title: "Stripchat Winterforu playing with boobs",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/9lhwwmxd5xag/stripchat-winterforu-playing-with-boobs",
      thumb: "",
      overlay: "https://i.ibb.co/G3JvdW3V/Stripchat-Winterforu-playing-with-boobs.jpg",
      duration: "2602",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/3hp449.mp4"
    },
    {
      id: "wf-v28",
      title: "Stripchat Winterforu",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/6alvcrp8xglx/stripchat-winterforu",
      thumb: "",
      overlay: "https://i.ibb.co/Dgbj3J6f/Stripchat-Winterforu.jpg",
      duration: "1444",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/jktfqp.mp4"
    },
    {
      id: "wf-v29",
      title: "Winterforu ()",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/np9lc82gqsew/winterforu",
      thumb: "",
      overlay: "https://i.ibb.co/PsDgDjyh/Winterforu.jpg",
      duration: "5954",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/nx8d95.mp4"
    },
    {
      id: "wf-v30",
      title: "winterforu ass show",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/7510gtkxwshs/winterforu-ass-show",
      thumb: "",
      overlay: "https://i.ibb.co/HTPQZ27S/winterforu-ass-show.jpg",
      duration: "423",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/r0f5zp.mp4"
    },
    {
      id: "wf-v31",
      title: "Winterforu Baby Masturbating Showing Beautiful Pussy Closeup",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/fht463hir04k/winterforu-baby-masturbating-showing-beautiful-pussy-closeup",
      thumb: "",
      overlay: "https://i.ibb.co/RtZWMdD/Winterforu-Baby-Masturbating-Showing-Beautiful-Pussy-Closeup.jpg",
      duration: "4781",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/9mb4g2.mp4"
    },
    {
      id: "wf-v32",
      title: "Winterforu BDSM – Chained Nipple Clamps & Dildo Sucking",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/95hnf1z3yq8u/winterforu-bdsm-chained-nipple-clamps-dildo-sucking",
      thumb: "",
      overlay: "https://i.ibb.co/0yz407SF/Winterforu-BDSM-Chained-Nipple-Clamps-Dildo-Sucking.png",
      duration: "196",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/rj92kh.mp4"
    },
    {
      id: "wf-v33",
      title: "winterforu boobs show",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/lds7e59bcm24/winterforu-boobs-show",
      thumb: "",
      overlay: "https://i.ibb.co/cS43nDdL/winterforu-boobs-show.jpg",
      duration: "302",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/azu2sb.mp4"
    },
    {
      id: "wf-v34",
      title: "Winterforu Fucking Dido in Pussy Harder",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/na4o2hklg857/winterforu-fucking-dido-in-pussy-harder",
      thumb: "",
      overlay: "https://i.ibb.co/ZRfPT2y0/Winterforu-Fucking-Dido-in-Pussy-Harder.jpg",
      duration: "179",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/6j8jdj.mp4"
    },
    {
      id: "wf-v35",
      title: "Winterforu Handcuffed and Hard Boobs Pinching",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/g9nz6bme2d97/winterforu-handcuffed-and-hard-boobs-pinching",
      thumb: "",
      overlay: "https://i.ibb.co/KpCnJwhf/Winterforu-Handcuffed-and-Hard-Boobs-Pinching.jpg",
      duration: "1171",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/3j8nlq.mp4"
    },
    {
      id: "wf-v36",
      title: "Winterforu in Sexy Red Dress Does Hard Dildo Deepthroat",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/x0td2p2flbtn/winterforu-in-sexy-red-dress-does-hard-dildo-deepthroat",
      thumb: "",
      overlay: "https://i.ibb.co/Kx0dpHpY/Winterforu-in-Sexy-Red-Dress-Does-Hard-Dildo-Deepthroat.jpg",
      duration: "5585",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/77y7mr.mp4"
    },
    {
      id: "wf-v37",
      title: "winterforu naked playing with lush harder",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/lgxxhp7etbrx/winterforu-naked-playing-with-lush-harder",
      thumb: "",
      overlay: "https://i.ibb.co/V0YXfhLZ/winterforu-naked-playing-with-lush-harder.jpg",
      duration: "303",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/zi1wff.mp4"
    },
    {
      id: "wf-v38",
      title: "Winterforu Nude Showing Masturbating",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/4au1dfidwkzf/winterforu-nude-showing-masturbating",
      thumb: "",
      overlay: "https://i.ibb.co/RksqcMdN/Winterforu-Nude-Showing-Masturbating.jpg",
      duration: "4018",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/4m2vyr.mp4"
    },
    {
      id: "wf-v39",
      title: "Winterforu Oiled Ass Hard Spanked",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/tv5fc10008oc/winterforu-oiled-ass-hard-spanked",
      thumb: "",
      overlay: "https://i.ibb.co/v6LhgvQf/Winterforu-Oiled-Ass-Hard-Spanked.jpg",
      duration: "361",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/coniit.mp4"
    },
    {
      id: "wf-v40",
      title: "Winterforu show ass slap",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/cjxnc86inlab/winterforu-show-ass-slap",
      thumb: "",
      overlay: "https://i.ibb.co/cSTxNRBm/Winterforu-show-ass-slap.jpg",
      duration: "1036",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/4ehbuc.mp4"
    },
    {
      id: "wf-v41",
      title: "Winterforu show boobies navel show hand Cup",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/53rp0nmp4j34/winterforu-show-boobies-navel-show-hand-cup",
      thumb: "",
      overlay: "https://i.ibb.co/HfFv1fjs/Winterforu-show-boobies-navel-show-hand-Cup.jpg",
      duration: "2192",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/95ens4.mp4"
    },
    {
      id: "wf-v42",
      title: "winterforu stripchat fullnude, fingering, close-up pussy, vibrator",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/bux9xpvj49ps/winterforu-stripchat-fullnude-fingering-close-up-pussy-vibrator",
      thumb: "",
      overlay: "https://i.ibb.co/DgzNK4G6/winterforu-stripchat-fullnude-fingering-close-up-pussy-vibrator.jpg",
      duration: "567",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/uv49lg.mp4"
    },
    {
      id: "wf-v43",
      title: "Winterforu Stripchat Girl Nude Pinch Nipple Sexy Tease",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/eax6e8i09rtn/winterforu-stripchat-girl-nude-pinch-nipple-sexy-tease",
      thumb: "",
      overlay: "https://i.ibb.co/bgNKsrdd/Winterforu-Stripchat-Girl-Nude-Pinch-Nipple-Sexy-Tease.jpg",
      duration: "273",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/uwc52v.mp4"
    },
    {
      id: "wf-v44",
      title: "winterforu stripchat recording video",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/42p3md1yom3j/winterforu-stripchat-recording-video",
      thumb: "",
      overlay: "https://i.ibb.co/CpLbG1cw/winterforu-stripchat-recording-video.jpg",
      duration: "1803",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/lfqh26.mp4"
    },
    {
      id: "wf-v45",
      title: "winterforu stripchat roleplay of slave bdsm with handcuffs and nipple clamps",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/dfm0sg6vuhao/winterforu-stripchat-roleplay-of-slave-bdsm-with-handcuffs-and-nipple-clamps",
      thumb: "",
      overlay: "https://i.ibb.co/ynbyxgQ0/winterforu-stripchat-roleplay-of-slave-bdsm-with-handcuffs-and-nipple-clamps.jpg",
      duration: "287",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/k022s9.mp4"
    },
    {
      id: "wf-v46",
      title: "Winterforu Wearing Tiny Orange Bra & Panty Gets Brutal BDSM Session - Clit Torture, Boob Slapping & Hard Nipple Play",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/rmrsv4k7v8aj/winterforu-wearing-tiny-orange-bra-panty-gets-brutal-bdsm-session-clit-torture-boob-slapping-hard-nipple-play",
      thumb: "",
      overlay: "https://i.ibb.co/8LfKbNVD/Winterforu-Wearing-Tiny-Orange-Bra-Panty-Gets-Brutal-BDSM-Session-Clit-Torture-Boob-Slapping.png",
      duration: "868",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/4vrdjs.mp4"
    },
    {
      id: "wf-v47",
      title: "winterforu boobs show",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/rh56ung0ktav/winterforu-boobs-show",
      thumb: "",
      overlay: "https://i.ibb.co/rGjvzZyZ/winterforu-boobs-show.jpg",
      duration: "371",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/lthi49.mp4"
    },
    {
      id: "wf-v48",
      title: "winterforu boobs show",
      tags: ["Exclusive"],
      src: "https://bysekoze.com/e/k8ilwc0fwyry/winterforu-boobs-show",
      thumb: "",
      overlay: "https://i.ibb.co/PsJhZ7MQ/winterforu-boobs-show.jpg",
      duration: "419",
      addedAt: "2026-07-13T12:00:00Z",
      model: "Winterforu",
      previewUrl: "https://files.catbox.moe/6hr5no.mp4"
    }
  ]
};
