import { SupModel } from '../sup-data';

export const winterforuData: Partial<SupModel> = {
  portrait: 'https://i.ibb.co/gFP89s4T/Porrarit.png',
  folderThumb: 'https://i.ibb.co/r2zZ4tt9/Folderthumb.webp',
  image: 'https://i.ibb.co/gFP89s4T/Porrarit.png',
  photos: [
    "https://i.ibb.co/spqmPtR0/1b8b05557bdc36286e62043353c49bf9.webp",
    "https://i.ibb.co/JRyc4CqH/407a85c0f2cd26490f5bf4959bd22c7f.webp",
    "https://i.ibb.co/MycYS42b/1440e933b85efde5cce2c273073f70b4.webp",
    "https://i.ibb.co/LHKbTnh/08336eb79200aeae4b92f4e28f6326c3.webp",
    "https://i.ibb.co/5h3Mz0hc/244592f5d81036eda14a1384bd2a9bda.webp",
    "https://i.ibb.co/v6mwqb2Y/b8d0aa2aca77817faa696b4da2082643.webp",
    "https://i.ibb.co/YrvmTCg/e07f93609ba564f74ffcced20f80bf9a.webp",
    "https://i.ibb.co/ns946Ksp/efffedae07f09dfbe5e39f6bc2f3acf0.webp",
    "https://i.ibb.co/whg0G90m/f40ef58894228304815dbaa876518543.webp",
    "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp",
    "https://i.ibb.co/gFP89s4T/Porrarit.png",
    "https://i.ibb.co/Pv4qGNWZ/profile-3.png"
  ],
  clips: [
    { title: "Short Clip 1", url: "https://files.catbox.moe/vcuwq4.mp4", thumbnail: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp" },
    { title: "Short Clip 2", url: "https://files.catbox.moe/i9kfs6.mp4", thumbnail: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp" },
    { title: "Short Clip 3", url: "https://files.catbox.moe/27gqcj.mp4", thumbnail: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp" },
    { title: "Short Clip 4", url: "https://files.catbox.moe/rl2axp.mp4", thumbnail: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp" },
    { title: "Short Clip 5", url: "https://files.catbox.moe/i5kkvp.mp4", thumbnail: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp" },
    { title: "Short Clip 6", url: "https://files.catbox.moe/758ee6.mp4", thumbnail: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp" },
    { title: "Short Clip 7", url: "https://files.catbox.moe/5e0e1l.mp4", thumbnail: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp" },
    { title: "Short Clip 8", url: "https://files.catbox.moe/h9oksm.mp4", thumbnail: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp" },
    { title: "Short Clip 9", url: "https://files.catbox.moe/uwdx3y.mp4", thumbnail: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp" },
    { title: "Short Clip 10", url: "https://files.catbox.moe/toctcf.mp4", thumbnail: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp" },
    { title: "Short Clip 11", url: "https://files.catbox.moe/b09pkk.mp4", thumbnail: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp" },
    { title: "Short Clip 12", url: "https://files.catbox.moe/6e7dj4.mp4", thumbnail: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp" },
    { title: "Short Clip 13", url: "https://files.catbox.moe/fnuxp6.mp4", thumbnail: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp" },
    { title: "Short Clip 14", url: "https://files.catbox.moe/upxliq.mp4", thumbnail: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp" },
    { title: "Short Clip 15", url: "https://files.catbox.moe/asbn6u.mp4", thumbnail: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp" },
    { title: "Short Clip 16", url: "https://files.catbox.moe/yrz9yw.mp4", thumbnail: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp" },
    { title: "Short Clip 17", url: "https://files.catbox.moe/j4a6dd.mp4", thumbnail: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp" },
    { title: "Short Clip 18", url: "https://files.catbox.moe/wbh071.mp4", thumbnail: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp" },
    { title: "Short Clip 19", url: "https://files.catbox.moe/xjo1c6.mp4", thumbnail: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp" },
  ],
  videos: [
    { id: "wf-c1", title: "Short Clip 1", src: "https://files.catbox.moe/vcuwq4.mp4", thumb: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "wf-c2", title: "Short Clip 2", src: "https://files.catbox.moe/i9kfs6.mp4", thumb: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "wf-c3", title: "Short Clip 3", src: "https://files.catbox.moe/27gqcj.mp4", thumb: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "wf-c4", title: "Short Clip 4", src: "https://files.catbox.moe/rl2axp.mp4", thumb: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "wf-c5", title: "Short Clip 5", src: "https://files.catbox.moe/i5kkvp.mp4", thumb: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "wf-c6", title: "Short Clip 6", src: "https://files.catbox.moe/758ee6.mp4", thumb: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "wf-c7", title: "Short Clip 7", src: "https://files.catbox.moe/5e0e1l.mp4", thumb: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "wf-c8", title: "Short Clip 8", src: "https://files.catbox.moe/h9oksm.mp4", thumb: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "wf-c9", title: "Short Clip 9", src: "https://files.catbox.moe/uwdx3y.mp4", thumb: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "wf-c10", title: "Short Clip 10", src: "https://files.catbox.moe/toctcf.mp4", thumb: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "wf-c11", title: "Short Clip 11", src: "https://files.catbox.moe/b09pkk.mp4", thumb: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "wf-c12", title: "Short Clip 12", src: "https://files.catbox.moe/6e7dj4.mp4", thumb: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "wf-c13", title: "Short Clip 13", src: "https://files.catbox.moe/fnuxp6.mp4", thumb: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "wf-c14", title: "Short Clip 14", src: "https://files.catbox.moe/upxliq.mp4", thumb: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "wf-c15", title: "Short Clip 15", src: "https://files.catbox.moe/asbn6u.mp4", thumb: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "wf-c16", title: "Short Clip 16", src: "https://files.catbox.moe/yrz9yw.mp4", thumb: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "wf-c17", title: "Short Clip 17", src: "https://files.catbox.moe/j4a6dd.mp4", thumb: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "wf-c18", title: "Short Clip 18", src: "https://files.catbox.moe/wbh071.mp4", thumb: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp", categories: ["Stripchat", "Short Clips"] },
    { id: "wf-c19", title: "Short Clip 19", src: "https://files.catbox.moe/xjo1c6.mp4", thumb: "https://i.ibb.co/r2zZ4tt9/Folderthumb.webp", categories: ["Stripchat", "Short Clips"] },
  ]
};
